using PdfEr.Core.Domain.Layout;
using PdfEr.Core.Domain.Styles;

namespace PdfEr.Core.Application.HtmlProcessing;

/// <summary>
/// Pass 2 (placement) of the box-tree layout pipeline, first slice: plain
/// Block Formatting Context only (docs/plans/phase-01-foundation.md). Given a
/// root <see cref="LayoutBox"/> (already box-generated by
/// <see cref="BoxTreeBuilder"/> and sized by <see cref="IntrinsicSizeCalculator"/>)
/// and a <see cref="ContainingBlock"/>, resolves each box's <see cref="BoxGeometry"/>
/// top-down: width fills the containing block (or resolves "width"/percentage),
/// height comes from content unless "height" is set, and block-level children
/// stack vertically.
///
/// Deliberately NOT implemented in this slice (separate, larger pieces of work):
/// - Margin collapsing (CSS 2.1 8.3.1) between ADJACENT SIBLINGS is implemented
///   (see CollapseMargins) — but parent/first-child, parent/last-child, and
///   empty-block self-collapsing are not: those need border/padding context to
///   flow across recursion levels (a child needs to know whether its parent has
///   top border/padding to decide if their margins collapse), which is a larger
///   change to the recursive structure than this slice makes.
/// - Inline Formatting Context / line boxes — an Inline/Text/Anonymous child is
///   given a single placeholder line box using FontSizeMm * a fixed line-height
///   factor, not real line-breaking (that's Phase 2/3 work). Anonymous blocks
///   (wrapping inline runs, see BoxTreeBuilder) are placed as an ordinary block
///   would be, with height derived from that placeholder.
/// - Floats, positioning (relative/absolute), tables, flex/grid — every non-Block
///   LayoutBoxKind is placed using the same plain block rules for now; each needs
///   its own placement algorithm in a later slice.
/// </summary>
public sealed class BlockPlacer
{
    // Matches the streaming pipeline's auto line-height factor
    // (LayoutEngine.cs: fontSize * 1.3f) so both pipelines agree on the
    // placeholder height used for inline content until real line boxes exist.
    private const float AutoLineHeightFactor = 1.3f;

    public void Place(LayoutBox box, ContainingBlock containingBlock, float x, float y)
    {
        var geometry = new BoxGeometry { X = x, Y = y };
        ApplyBoxModel(ref geometry, box.Style);

        geometry.Width = ResolveWidth(box, containingBlock, geometry);

        var contentWidth = geometry.Width - geometry.PaddingLeft - geometry.PaddingRight
            - geometry.BorderLeft - geometry.BorderRight;
        var childContainingBlock = new ContainingBlock(Math.Max(0, contentWidth), containingBlock.Height, containingBlock.HeightIsDefinite);

        var contentTop = y + geometry.PaddingTop + geometry.BorderTop;
        var contentLeft = x + geometry.PaddingLeft + geometry.BorderLeft;
        var cursorY = contentTop;

        if (box.Kind == LayoutBoxKind.Text)
        {
            geometry.Height = box.Style.FontSizeMm * AutoLineHeightFactor;
        }
        else if (box.Children.Count == 0)
        {
            geometry.Height = 0;
        }
        else
        {
            float? previousMarginBottom = null;

            foreach (var child in box.Children)
            {
                // Margin-top must be known before placing the child (it offsets
                // where the child's border box starts), so it's parsed here
                // rather than only inside the recursive Place call.
                var marginTop = ParseLengthMm(child.Style.GetPropertyValue("margin-top"));

                // CSS 2.1 8.3.1 adjacent-sibling collapsing: this child's margin-top
                // and the previous sibling's margin-bottom collapse into a single
                // margin rather than adding. Only applies between siblings in the
                // same block formatting context — the first child has no previous
                // sibling to collapse with, so its margin-top applies in full here
                // (parent/first-child collapsing is a separate, not-yet-implemented
                // case; see class remarks).
                if (previousMarginBottom.HasValue)
                {
                    cursorY -= previousMarginBottom.Value; // undo the uncollapsed margin already added
                    cursorY += CollapseMargins(previousMarginBottom.Value, marginTop);
                }
                else
                {
                    cursorY += marginTop;
                }

                Place(child, childContainingBlock, contentLeft, cursorY);

                cursorY += child.Geometry.Height;
                previousMarginBottom = child.Geometry.MarginBottom;
                cursorY += child.Geometry.MarginBottom;
            }
            geometry.Height = cursorY - contentTop;
        }

        var explicitHeight = ResolveExplicitLength(box.Style.GetPropertyValue("height"), containingBlock.Height, containingBlock.HeightIsDefinite);
        if (explicitHeight.HasValue)
            geometry.Height = explicitHeight.Value;

        box.Geometry = geometry;
    }

    /// <summary>
    /// CSS 2.1 8.3.1 general collapsing formula: when all collapsing margins are
    /// non-negative, the result is their max; when negative margins are
    /// involved, take the max of the positives and add the min (most negative)
    /// of the negatives. With exactly two margins this reduces to the common
    /// cases (both positive -> max, both negative -> min, mixed -> sum).
    /// </summary>
    private static float CollapseMargins(float a, float b)
    {
        var maxPositive = Math.Max(Math.Max(a, 0), Math.Max(b, 0));
        var minNegative = Math.Min(Math.Min(a, 0), Math.Min(b, 0));
        return maxPositive + minNegative;
    }

    private static float ResolveWidth(LayoutBox box, ContainingBlock containingBlock, BoxGeometry geometry)
    {
        var explicitWidth = ResolveExplicitLength(box.Style.GetPropertyValue("width"), containingBlock.Width, true);
        if (explicitWidth.HasValue)
            return explicitWidth.Value;

        if (box.Kind is LayoutBoxKind.InlineBlock or LayoutBoxKind.Inline)
        {
            // Shrink-to-fit (CSS 2.1 10.3.9): bounded by the containing block,
            // sized from Pass 1's intrinsic max-content width when available.
            var available = Math.Max(0, containingBlock.Width - geometry.PaddingLeft - geometry.PaddingRight - geometry.BorderLeft - geometry.BorderRight);
            var maxContent = box.Intrinsic?.MaxContentWidth ?? available;
            return Math.Min(available, maxContent) + geometry.PaddingLeft + geometry.PaddingRight + geometry.BorderLeft + geometry.BorderRight;
        }

        // Default: a block box fills its containing block's width (CSS 2.1 10.3.3).
        return containingBlock.Width;
    }

    private static float? ResolveExplicitLength(string? value, float referenceDimension, bool referenceIsDefinite)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        value = value.Trim().ToLowerInvariant();
        if (value == "auto") return null;

        if (value.EndsWith('%'))
        {
            if (!referenceIsDefinite) return null; // CSS 2.1 10.5: % height needs a definite containing-block height
            return float.TryParse(value[..^1], out var pct) ? referenceDimension * pct / 100f : null;
        }

        var mm = ParseLengthMm(value);
        return mm > 0 || value is "0" or "0px" or "0pt" or "0mm" ? mm : null;
    }

    private static void ApplyBoxModel(ref BoxGeometry geometry, ComputedStyle style)
    {
        geometry.PaddingTop = ParseLengthMm(style.GetPropertyValue("padding-top"));
        geometry.PaddingBottom = ParseLengthMm(style.GetPropertyValue("padding-bottom"));
        geometry.PaddingLeft = ParseLengthMm(style.GetPropertyValue("padding-left"));
        geometry.PaddingRight = ParseLengthMm(style.GetPropertyValue("padding-right"));

        geometry.BorderTop = ParseLengthMm(style.GetPropertyValue("border-top-width"));
        geometry.BorderBottom = ParseLengthMm(style.GetPropertyValue("border-bottom-width"));
        geometry.BorderLeft = ParseLengthMm(style.GetPropertyValue("border-left-width"));
        geometry.BorderRight = ParseLengthMm(style.GetPropertyValue("border-right-width"));

        geometry.MarginTop = ParseLengthMm(style.GetPropertyValue("margin-top"));
        geometry.MarginBottom = ParseLengthMm(style.GetPropertyValue("margin-bottom"));
        geometry.MarginLeft = ParseLengthMm(style.GetPropertyValue("margin-left"));
        geometry.MarginRight = ParseLengthMm(style.GetPropertyValue("margin-right"));
    }

    // Same unit table as IntrinsicSizeCalculator.ParseLengthMm / LayoutEngine.ParseLength
    // (mm-native layout units, see memory [[pdfer-layout-units]]).
    private static float ParseLengthMm(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return 0;
        value = value.Trim().ToLowerInvariant();
        if (value is "0" or "0px" or "0pt" or "0mm" or "auto" or "none") return 0;
        if (value is "thin") return 0.5f;
        if (value is "medium") return 1f;
        if (value is "thick") return 2f;

        if (value.EndsWith("mm")) return float.TryParse(value[..^2], out var v) ? v : 0;
        if (value.EndsWith("pt")) return float.TryParse(value[..^2], out var v) ? v * 0.3528f : 0;
        if (value.EndsWith("px")) return float.TryParse(value[..^2], out var v) ? v * 0.2646f : 0;
        if (value.EndsWith("cm")) return float.TryParse(value[..^2], out var v) ? v * 10f : 0;
        if (value.EndsWith("in")) return float.TryParse(value[..^2], out var v) ? v * 25.4f : 0;
        if (float.TryParse(value, out var num)) return num;
        return 0;
    }
}
