using PdfEr.Core.Application.Interfaces;
using PdfEr.Core.Domain.Layout;
using PdfEr.Core.Domain.Styles;
using PdfEr.Core.Domain.Typography;

namespace PdfEr.Core.Application.HtmlProcessing;

/// <summary>
/// Pass 2 (placement) of the box-tree layout pipeline (docs/plans/phase-01-foundation.md).
/// Given a root <see cref="LayoutBox"/> (already box-generated by
/// <see cref="BoxTreeBuilder"/> and sized by <see cref="IntrinsicSizeCalculator"/>)
/// and a <see cref="ContainingBlock"/>, resolves each box's <see cref="BoxGeometry"/>
/// top-down: width fills the containing block (or resolves "width"/percentage),
/// height comes from content unless "height" is set, block-level children stack
/// vertically (Block Formatting Context), and inline-level children wrap into real
/// lines bounded by content width (Inline Formatting Context, see PlaceInlineContent).
///
/// Deliberately NOT implemented in this slice (separate, larger pieces of work):
/// - Margin collapsing (CSS 2.1 8.3.1) between ADJACENT SIBLINGS is implemented
///   (see CollapseMargins) — but parent/first-child, parent/last-child, and
///   empty-block self-collapsing are not: those need border/padding context to
///   flow across recursion levels (a child needs to know whether its parent has
///   top border/padding to decide if their margins collapse), which is a larger
///   change to the recursive structure than this slice makes.
/// - Line-breaking uses whitespace word boundaries (matching IntrinsicSizeCalculator's
///   min-content definition), not full UAX#14 (that's Phase 3 text work). No
///   hyphenation, no bidi, no per-run font/size changes within a line (a run's
///   metrics come from the LayoutBox that owns the text, since BoxTreeBuilder does
///   not yet merge sibling inline runs with different styles into one line).
/// - Floats, positioning (relative/absolute), tables, flex/grid — every non-Block
///   LayoutBoxKind is placed using the same plain block rules for now; each needs
///   its own placement algorithm in a later slice.
/// </summary>
public sealed class BlockPlacer
{
    // Matches the streaming pipeline's auto line-height factor
    // (LayoutEngine.cs: fontSize * 1.3f) so both pipelines agree on line height.
    private const float AutoLineHeightFactor = 1.3f;
    private const float PtToMm = 0.3528f;

    private readonly IFontRegistry? _fontRegistry;

    /// <summary>
    /// fontRegistry is optional so existing callers/tests that don't need real
    /// line-breaking (or don't have a font registry handy) keep working: without
    /// it, inline content falls back to the single-placeholder-line behavior
    /// this class originally shipped with.
    /// </summary>
    public BlockPlacer(IFontRegistry? fontRegistry = null)
    {
        _fontRegistry = fontRegistry;
    }

    public void Place(LayoutBox box, ContainingBlock containingBlock, float x, float y)
    {
        var geometry = new BoxGeometry { X = x, Y = y };
        ApplyBoxModel(ref geometry, box.Style);

        geometry.Width = ResolveWidth(box, containingBlock, geometry);
        geometry.Width = ClampToMinMax(geometry.Width, box.Style, containingBlock.Width,
            "min-width", "max-width", geometry, isWidth: true);
        geometry.X = ApplyAutoMarginCentering(box, geometry, containingBlock, x);

        var contentWidth = geometry.Width - geometry.PaddingLeft - geometry.PaddingRight
            - geometry.BorderLeft - geometry.BorderRight;
        var childContainingBlock = new ContainingBlock(Math.Max(0, contentWidth), containingBlock.Height, containingBlock.HeightIsDefinite);

        var contentTop = y + geometry.PaddingTop + geometry.BorderTop;
        var contentLeft = geometry.X + geometry.PaddingLeft + geometry.BorderLeft;
        var cursorY = contentTop;

        if (box.Kind == LayoutBoxKind.Text)
        {
            geometry.Height = ResolveLineHeightMm(box.Style);
        }
        else if (box.Kind == LayoutBoxKind.LineBreak)
        {
            // Forces vertical space like a single empty line, matching
            // BreakHandler's legacy behavior (a text run consisting of "\n").
            geometry.Height = ResolveLineHeightMm(box.Style);
        }
        else if (box.Kind == LayoutBoxKind.Image)
        {
            // An <img>'s box has no children to derive height from -- its
            // size comes from its own pixel dimensions (converted to mm at
            // 96 DPI by BoxTreeBuilder), not the containing block.
            const float PxToMm = 25.4f / 96f;
            geometry.Width = box.ImagePixelWidth * PxToMm;
            geometry.Height = box.ImagePixelHeight * PxToMm;
        }
        else if (box.Children.Count == 0)
        {
            geometry.Height = 0;
        }
        else if (_fontRegistry != null && box.Children.All(IsInlineLevel))
        {
            // Inline Formatting Context: this box's children are all inline-level
            // (BoxTreeBuilder guarantees this for Anonymous boxes, and it's also
            // true for a plain block whose only children are text/inline, e.g. <p>
            // with no nested block elements). Wrap them into real lines instead of
            // stacking each one as if it were its own block.
            geometry.Height = PlaceInlineContent(box, childContainingBlock, contentLeft, contentTop);
        }
        else
        {
            float? previousMarginBottom = null;

            foreach (var child in box.Children)
            {
                // Margin-top must be known before placing the child (it offsets
                // where the child's border box starts), so it's parsed here
                // rather than only inside the recursive Place call.
                var marginTop = ParseLengthMm(child.Style.GetPropertyValue("margin-top"));

                // CSS 2.1 8.3.1 adjacent-sibling collapsing: this child's margin-top
                // and the previous sibling's margin-bottom collapse into a single
                // margin rather than adding. Only applies between siblings in the
                // same block formatting context — the first child has no previous
                // sibling to collapse with, so its margin-top applies in full here
                // (parent/first-child collapsing is a separate, not-yet-implemented
                // case; see class remarks).
                if (previousMarginBottom.HasValue)
                {
                    cursorY -= previousMarginBottom.Value; // undo the uncollapsed margin already added
                    cursorY += CollapseMargins(previousMarginBottom.Value, marginTop);
                }
                else
                {
                    cursorY += marginTop;
                }

                Place(child, childContainingBlock, contentLeft, cursorY);

                cursorY += child.Geometry.Height;
                previousMarginBottom = child.Geometry.MarginBottom;
                cursorY += child.Geometry.MarginBottom;
            }
            geometry.Height = cursorY - contentTop;
        }

        var explicitHeight = ResolveExplicitLength(box.Style.GetPropertyValue("height"), containingBlock.Height, containingBlock.HeightIsDefinite);
        if (explicitHeight.HasValue)
        {
            var paddingBorderHeight = geometry.PaddingTop + geometry.PaddingBottom + geometry.BorderTop + geometry.BorderBottom;
            geometry.Height = IsBorderBox(box.Style) ? explicitHeight.Value : explicitHeight.Value + paddingBorderHeight;
        }

        geometry.Height = ClampToMinMax(geometry.Height, box.Style, containingBlock.Height,
            "min-height", "max-height", geometry, isWidth: false);

        box.Geometry = geometry;
    }

    /// <summary>
    /// Clamps a resolved border-box dimension to CSS min-*/max-* (CSS2.1 10.4/10.7).
    /// min-width/min-height/max-width/max-height are specified against the
    /// content box by default (same box-sizing rule as width/height itself), so
    /// padding+border is added on top before clamping unless box-sizing:border-box
    /// is set. max-* of "none" (or an unresolvable percentage against an
    /// indefinite containing block) is not applied, matching ResolveExplicitLength.
    /// </summary>
    private static float ClampToMinMax(float borderBoxValue, ComputedStyle style, float containingBlockDimension,
        string minProperty, string maxProperty, BoxGeometry geometry, bool isWidth)
    {
        var paddingBorder = isWidth
            ? geometry.PaddingLeft + geometry.PaddingRight + geometry.BorderLeft + geometry.BorderRight
            : geometry.PaddingTop + geometry.PaddingBottom + geometry.BorderTop + geometry.BorderBottom;
        var borderBox = IsBorderBox(style);

        var min = ResolveExplicitLength(style.GetPropertyValue(minProperty), containingBlockDimension, true);
        if (min.HasValue)
        {
            var minBorderBox = borderBox ? min.Value : min.Value + paddingBorder;
            if (borderBoxValue < minBorderBox) borderBoxValue = minBorderBox;
        }

        var maxRaw = style.GetPropertyValue(maxProperty)?.Trim().ToLowerInvariant();
        if (maxRaw != "none")
        {
            var max = ResolveExplicitLength(maxRaw, containingBlockDimension, true);
            if (max.HasValue)
            {
                var maxBorderBox = borderBox ? max.Value : max.Value + paddingBorder;
                if (borderBoxValue > maxBorderBox) borderBoxValue = maxBorderBox;
            }
        }

        return borderBoxValue;
    }

    /// <summary>
    /// CSS 2.1 10.3.3: for an in-flow block-level box, "margin-left"/"margin-right:
    /// auto" absorb the extra space between the box's border-box width and its
    /// containing block's width. Both auto -> centered (extra space split evenly);
    /// only one auto -> that side absorbs all the extra space; neither auto ->
    /// no shift (the box stays at its containing block's content-box origin, x).
    /// Only applies to Block-kind boxes -- inline-level and inline-block boxes
    /// don't participate in this rule.
    /// </summary>
    private static float ApplyAutoMarginCentering(LayoutBox box, BoxGeometry geometry, ContainingBlock containingBlock, float x)
    {
        if (box.Kind != LayoutBoxKind.Block) return x;

        var marginLeftRaw = box.Style.GetPropertyValue("margin-left")?.Trim().ToLowerInvariant();
        var marginRightRaw = box.Style.GetPropertyValue("margin-right")?.Trim().ToLowerInvariant();
        bool leftAuto = marginLeftRaw == "auto";
        bool rightAuto = marginRightRaw == "auto";
        if (!leftAuto && !rightAuto) return x;

        var extraSpace = containingBlock.Width - geometry.Width;
        if (extraSpace <= 0) return x;

        if (leftAuto && rightAuto) return x + extraSpace / 2f; // centered
        if (leftAuto) return x + extraSpace; // margin-left absorbs everything, box hugs the right edge
        return x; // margin-right absorbs everything, box stays at the left edge
    }

    /// <summary>
    /// CSS 2.1 10.8.1 "line-height": a unitless number is a multiplier of this
    /// element's own font-size (e.g. "1.5" -> 1.5x); a length or percentage
    /// resolves to an absolute distance (percentage of font-size); "normal" or
    /// absent falls back to AutoLineHeightFactor, matching the streaming
    /// pipeline's existing convention (memory [[pdfer-layout-units]]) so both
    /// pipelines agree when no explicit line-height is set.
    /// </summary>
    private static float ResolveLineHeightMm(ComputedStyle style)
    {
        var raw = style.GetPropertyValue("line-height")?.Trim().ToLowerInvariant();
        if (string.IsNullOrEmpty(raw) || raw == "normal")
            return style.FontSizeMm * AutoLineHeightFactor;

        if (raw.EndsWith('%'))
        {
            return float.TryParse(raw[..^1], out var pct)
                ? style.FontSizeMm * pct / 100f
                : style.FontSizeMm * AutoLineHeightFactor;
        }

        // A bare number is a multiplier of font-size (not an absolute length).
        if (float.TryParse(raw, out var multiplier))
            return style.FontSizeMm * multiplier;

        // Otherwise it's a length (px/pt/mm/etc.) -- an absolute line-height,
        // not scaled by font-size.
        var lengthMm = CssLengthParser.ParseLengthMm(raw);
        return lengthMm > 0 ? lengthMm : style.FontSizeMm * AutoLineHeightFactor;
    }

    private static bool IsInlineLevel(LayoutBox box) =>
        box.Kind is LayoutBoxKind.Text or LayoutBoxKind.Inline or LayoutBoxKind.Anonymous
            or LayoutBoxKind.Image or LayoutBoxKind.LineBreak;

    /// <summary>
    /// One atomic unit of inline content for line-breaking purposes: either a
    /// single word (no internal break opportunities — CSS's min-content
    /// definition, matching IntrinsicSizeCalculator), an image, or a forced
    /// line break. Whitespace between words is not its own item; it is implied
    /// between consecutive Word items on the same line (one space-advance-width
    /// gap), matching how MeasureText in IntrinsicSizeCalculator treats it.
    /// </summary>
    private sealed record InlineItem(InlineItemKind Kind, string Text, float WidthMm, ComputedStyle Style, LayoutBox? ImageSource);

    private enum InlineItemKind { Word, Image, ForcedBreak }

    /// <summary>
    /// Real Inline Formatting Context line-breaking: flattens this box's
    /// inline-level descendants into words/images/forced-breaks, greedily packs
    /// them into lines no wider than the containing block's content width, and
    /// rewrites box.Children into one placed Text/Image LayoutBox per visual
    /// line segment (so BoxTreePaintAdapter's existing Text/Image flattening
    /// keeps working unchanged). Returns the total content height consumed.
    /// </summary>
    private float PlaceInlineContent(LayoutBox box, ContainingBlock containingBlock, float contentLeft, float contentTop)
    {
        var items = new List<InlineItem>();
        foreach (var child in box.Children)
            CollectInlineItems(child, items);

        var maxWidth = Math.Max(0, containingBlock.Width);
        var spaceWidthMm = items.Count > 0 ? items[0].Style.FontSizeMm * 0.28f : 0; // approx space width

        // CSS 2.1 16.1 "text-indent": shifts the first formatted line only.
        // Negative values are allowed (outdent); resolves against the
        // containing block width for percentages, same as ResolveExplicitLength.
        var textIndentMm = CssLengthParser.ParseCssLengthMm(box.Style.GetPropertyValue("text-indent"), containingBlock.Width);
        var firstLineMaxWidth = Math.Max(0, maxWidth - textIndentMm);

        var lines = new List<List<InlineItem>>();
        var currentLine = new List<InlineItem>();
        float currentLineWidth = 0;

        foreach (var item in items)
        {
            var currentLineMaxWidth = lines.Count == 0 ? firstLineMaxWidth : maxWidth;

            if (item.Kind == InlineItemKind.ForcedBreak)
            {
                lines.Add(currentLine);
                currentLine = new List<InlineItem>();
                currentLineWidth = 0;
                continue;
            }

            var neededWidth = item.WidthMm + (currentLine.Count > 0 ? spaceWidthMm : 0);
            if (currentLine.Count > 0 && currentLineWidth + neededWidth > currentLineMaxWidth)
            {
                lines.Add(currentLine);
                currentLine = new List<InlineItem>();
                currentLineWidth = 0;
                neededWidth = item.WidthMm;
            }

            currentLine.Add(item);
            currentLineWidth += neededWidth;
        }
        if (currentLine.Count > 0 || lines.Count == 0)
            lines.Add(currentLine);

        var textAlign = box.Style.GetPropertyValue("text-align")?.Trim().ToLowerInvariant() ?? "left";

        var newChildren = new List<LayoutBox>();
        float cursorY = contentTop;

        for (int lineIndex = 0; lineIndex < lines.Count; lineIndex++)
        {
            var line = lines[lineIndex];
            bool isLastLine = lineIndex == lines.Count - 1;

            float lineHeight = line.Count > 0
                ? line.Max(i => i.Kind == InlineItemKind.Image ? ImageHeightMm(i.ImageSource!) : ResolveLineHeightMm(i.Style))
                : (items.Count > 0 ? ResolveLineHeightMm(items[0].Style) : 0);

            bool isFirstLine = lineIndex == 0;
            float lineMaxWidth = isFirstLine ? firstLineMaxWidth : maxWidth;

            // Natural (left-aligned) width of this line: sum of item widths plus
            // one space gap between each pair of items.
            float naturalWidth = line.Count > 0
                ? line.Sum(i => i.WidthMm) + spaceWidthMm * (line.Count - 1)
                : 0;
            float extraSpace = Math.Max(0, lineMaxWidth - naturalWidth);

            // CSS 2.1 16.2: "justify" stretches inter-word space, but the LAST
            // line of a justified block is left-aligned, not stretched, so it
            // doesn't look like the last line is straining to fill the width.
            bool justifyThisLine = textAlign == "justify" && !isLastLine && line.Count > 1;

            float lineStartX = contentLeft + (isFirstLine ? textIndentMm : 0);
            float effectiveSpaceWidth = spaceWidthMm;
            if (justifyThisLine)
            {
                effectiveSpaceWidth = spaceWidthMm + extraSpace / (line.Count - 1);
            }
            else if (textAlign == "center")
            {
                lineStartX += extraSpace / 2f;
            }
            else if (textAlign == "right")
            {
                lineStartX += extraSpace;
            }

            float cursorX = lineStartX;
            for (int i = 0; i < line.Count; i++)
            {
                var item = line[i];
                if (i > 0) cursorX += effectiveSpaceWidth;

                if (item.Kind == InlineItemKind.Image)
                {
                    var imgBox = item.ImageSource!;
                    var placedImg = new LayoutBox
                    {
                        TagName = "img",
                        Kind = LayoutBoxKind.Image,
                        Style = imgBox.Style,
                        ImageSource = imgBox.ImageSource,
                        ImageData = imgBox.ImageData,
                        ImagePixelWidth = imgBox.ImagePixelWidth,
                        ImagePixelHeight = imgBox.ImagePixelHeight,
                        Geometry = new BoxGeometry { X = cursorX, Y = cursorY, Width = item.WidthMm, Height = lineHeight },
                    };
                    newChildren.Add(placedImg);
                }
                else
                {
                    var placedText = new LayoutBox
                    {
                        Kind = LayoutBoxKind.Text,
                        TextContent = item.Text,
                        Style = item.Style,
                        Geometry = new BoxGeometry { X = cursorX, Y = cursorY, Width = item.WidthMm, Height = lineHeight },
                    };
                    newChildren.Add(placedText);
                }

                cursorX += item.WidthMm;
            }

            cursorY += lineHeight;
        }

        box.Children.Clear();
        box.Children.AddRange(newChildren);

        return cursorY - contentTop;
    }

    private float ImageHeightMm(LayoutBox imageBox)
    {
        const float PxToMm = 25.4f / 96f;
        return imageBox.ImagePixelHeight * PxToMm;
    }

    /// <summary>
    /// Recursively flattens a LayoutBox subtree into InlineItems: a Text box's
    /// content is split on whitespace into Word items (matching
    /// IntrinsicSizeCalculator's word-boundary min-content definition); an
    /// Image becomes one atomic item; a LineBreak becomes a ForcedBreak;
    /// Inline/Anonymous containers are walked for their children.
    /// </summary>
    private void CollectInlineItems(LayoutBox box, List<InlineItem> items)
    {
        switch (box.Kind)
        {
            case LayoutBoxKind.Text:
                var text = box.TextContent ?? "";
                foreach (var word in text.Split(new[] { ' ', '\t', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                    items.Add(new InlineItem(InlineItemKind.Word, word, MeasureWordWidthMm(word, box.Style), box.Style, null));
                break;

            case LayoutBoxKind.Image:
                const float PxToMm = 25.4f / 96f;
                items.Add(new InlineItem(InlineItemKind.Image, "", box.ImagePixelWidth * PxToMm, box.Style, box));
                break;

            case LayoutBoxKind.LineBreak:
                items.Add(new InlineItem(InlineItemKind.ForcedBreak, "", 0, box.Style, null));
                break;

            default:
                foreach (var child in box.Children)
                    CollectInlineItems(child, items);
                break;
        }
    }

    /// <summary>
    /// Measures a single word's width using real font-metric advance widths,
    /// mirroring IntrinsicSizeCalculator.MeasureText's per-character summation
    /// (kept as a separate implementation here since BlockPlacer doesn't share
    /// an instance with IntrinsicSizeCalculator, only the same IFontRegistry).
    /// </summary>
    private float MeasureWordWidthMm(string word, ComputedStyle style)
    {
        if (word.Length == 0 || _fontRegistry == null) return 0;

        var fontFamily = style.GetPropertyValue("font-family") ?? "DejaVu Sans";
        var metrics = _fontRegistry.GetMetrics(fontFamily, ResolveFontStyle(style), style.FontSizePt);
        if (metrics == null)
            return word.Length * style.FontSizeMm * 0.5f;

        float widthPt = 0;
        foreach (var ch in word)
            widthPt += metrics.AdvanceWidths.TryGetValue(ch, out var w) ? w : metrics.SizePoints * 0.5f;

        return widthPt * PtToMm;
    }

    private static FontStyle ResolveFontStyle(ComputedStyle style)
    {
        var weight = style.GetPropertyValue("font-weight");
        var fontStyleValue = style.GetPropertyValue("font-style");

        bool bold = weight is "bold" or "700" or "800" or "900" ||
            (weight != null && int.TryParse(weight, out var w) && w >= 700);
        bool italic = fontStyleValue is "italic" or "oblique";

        if (bold && italic) return FontStyle.BoldItalic;
        if (bold) return FontStyle.Bold;
        if (italic) return FontStyle.Italic;
        return FontStyle.Regular;
    }

    /// <summary>
    /// CSS 2.1 8.3.1 general collapsing formula: when all collapsing margins are
    /// non-negative, the result is their max; when negative margins are
    /// involved, take the max of the positives and add the min (most negative)
    /// of the negatives. With exactly two margins this reduces to the common
    /// cases (both positive -> max, both negative -> min, mixed -> sum).
    /// </summary>
    private static float CollapseMargins(float a, float b)
    {
        var maxPositive = Math.Max(Math.Max(a, 0), Math.Max(b, 0));
        var minNegative = Math.Min(Math.Min(a, 0), Math.Min(b, 0));
        return maxPositive + minNegative;
    }

    /// <summary>
    /// CSS "box-sizing": whether the "width"/"height" properties specify the
    /// content box (default, CSS2.1) or the border box (box-sizing: border-box).
    /// BoxGeometry.Width/Height are always border-box (matching the legacy
    /// BlockBox model), so a content-box "width" needs padding+border added on
    /// top to become the border-box geometry width.
    /// </summary>
    private static bool IsBorderBox(ComputedStyle style) =>
        style.GetPropertyValue("box-sizing")?.Trim().ToLowerInvariant() == "border-box";

    private static float ResolveWidth(LayoutBox box, ContainingBlock containingBlock, BoxGeometry geometry)
    {
        var paddingBorder = geometry.PaddingLeft + geometry.PaddingRight + geometry.BorderLeft + geometry.BorderRight;

        var explicitWidth = ResolveExplicitLength(box.Style.GetPropertyValue("width"), containingBlock.Width, true);
        if (explicitWidth.HasValue)
            return IsBorderBox(box.Style) ? explicitWidth.Value : explicitWidth.Value + paddingBorder;

        if (box.Kind is LayoutBoxKind.InlineBlock or LayoutBoxKind.Inline)
        {
            // Shrink-to-fit (CSS 2.1 10.3.9): bounded by the containing block,
            // sized from Pass 1's intrinsic max-content width when available.
            var available = Math.Max(0, containingBlock.Width - paddingBorder);
            var maxContent = box.Intrinsic?.MaxContentWidth ?? available;
            return Math.Min(available, maxContent) + paddingBorder;
        }

        // Default: a block box fills its containing block's width (CSS 2.1 10.3.3).
        // Border-box width already includes padding/border here (the containing
        // block's content width is a border-box quantity for its children), so
        // box-sizing doesn't change this branch -- it only matters when "width"
        // is explicit.
        return containingBlock.Width;
    }

    private static float? ResolveExplicitLength(string? value, float referenceDimension, bool referenceIsDefinite)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        value = value.Trim().ToLowerInvariant();
        if (value == "auto") return null;

        if (value.EndsWith('%'))
        {
            if (!referenceIsDefinite) return null; // CSS 2.1 10.5: % height needs a definite containing-block height
            return float.TryParse(value[..^1], out var pct) ? referenceDimension * pct / 100f : null;
        }

        var mm = ParseLengthMm(value);
        return mm > 0 || value is "0" or "0px" or "0pt" or "0mm" ? mm : null;
    }

    private static void ApplyBoxModel(ref BoxGeometry geometry, ComputedStyle style)
    {
        geometry.PaddingTop = ParseLengthMm(style.GetPropertyValue("padding-top"));
        geometry.PaddingBottom = ParseLengthMm(style.GetPropertyValue("padding-bottom"));
        geometry.PaddingLeft = ParseLengthMm(style.GetPropertyValue("padding-left"));
        geometry.PaddingRight = ParseLengthMm(style.GetPropertyValue("padding-right"));

        geometry.BorderTop = ParseLengthMm(style.GetPropertyValue("border-top-width"));
        geometry.BorderBottom = ParseLengthMm(style.GetPropertyValue("border-bottom-width"));
        geometry.BorderLeft = ParseLengthMm(style.GetPropertyValue("border-left-width"));
        geometry.BorderRight = ParseLengthMm(style.GetPropertyValue("border-right-width"));

        geometry.MarginTop = ParseLengthMm(style.GetPropertyValue("margin-top"));
        geometry.MarginBottom = ParseLengthMm(style.GetPropertyValue("margin-bottom"));
        geometry.MarginLeft = ParseLengthMm(style.GetPropertyValue("margin-left"));
        geometry.MarginRight = ParseLengthMm(style.GetPropertyValue("margin-right"));
    }

    // Delegates to CssLengthParser (single shared implementation — see that
    // file's remarks for why this and two other identical copies were
    // consolidated). Kept as a thin wrapper so call sites in this file don't change.
    private static float ParseLengthMm(string? value) => CssLengthParser.ParseLengthMm(value);
}
